name: Run tests and upload coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20" # or your desired version

      - name: Install dependencies
        run: npm install

      - name: Make jest executable
        run: chmod +x ./node_modules/.bin/jest

      - name: Run tests with coverage
        run: npm test

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ARTMashimbyi/ConstitutionVaultDB
